<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 * 
 */
?>
<?php
/**
 * Suggeste store template
 *
 * @var $block \Risecommerce\AutoLanguageSwitcher\Block\SuggestedStore
 */
?>
<script>
    require([
            'Magento_Ui/js/modal/alert',
            'jquery',
            'jquery/ui',
            'jquery/jquery.cookie',
            'domReady!'], function (alert, $) {

        var ck = 'mfals-suggested-store';
        if (!$.cookie(ck)) {

            var config = <?= $block->getConfig() ?>;
            var url = config.api_url + "rest/V1/mfals/suggested-store?time=" + Date.now() + '&rand=' + Math.random()
                +'&current_url=' + config.current_url;
            $.getJSON(url, function (data) {
                data = JSON.parse(data);

                var date = new Date();
                date.setTime(date.getTime() + (2 * 86400 * 1000));
                $.cookie(ck, 1, {path: '/', expires: date});

                if (!data.redirect_url) return;
                alert({
                    title: $.mage.__(data.message) ,
                    class: 'als-suggested-store-popup',
                    buttons: [
                        {
                            text: data.yes_label + ( (data.yes_label != $.mage.__('Yes')) ? (' (' + $.mage.__('Yes') + ')') : '' ),
                            class: 'action-primary action-accept',
                            click: function (event) {
                              window.location = data.redirect_url;
                            }
                        },
                        {
                            text: data.no_label + ( (data.no_label != $.mage.__('No')) ? (' (' + $.mage.__('No') + ')') : '' ),
                            class: 'action-secondary action-dismiss',
                            click: function (event) {
                              this.closeModal(event);
                            }
                        }
                    ]
                });
            });
        }
    });
</script>
